arso_helpersite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cctvcounter.urls')),
    path('', include('businessreport.urls')),
    path('', include('js_apps.urls')),
]

businessreport/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from . import views
app_name = 'businessreport'

urlpatterns = [
    path('bu/talamban/', views.tmbindex, name='tmbrep'),
    path('bu/labangon/', views.labindex, name='labrep'),
    path('bu/kalimpyo/', views.kalindex, name='kalrep'),
    path("bu/moonlit/", views.moonindex, name="moonrep"),
    path('detalye/', views.detail, name='detailrep'),
    path("ajax/get_data_yesterday/",
         views.get_data_yesterday, name='get_data_yesterday'),
    path('', views.uli, name='uli'),
    path('about/', views.about, name="about"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

js_apps/urls.py
from django.urls import path, include
from . import views
app_name = 'js_app'
urlpatterns = [
    path('app/capsealcounter', views.capsealCnt, name='capsealcounter'),
    path('app/moneycounter', views.moneyCnt, name='moneycounter'),
    path('app/labreport', views.labReport, name="labreport")
]

businessreport/models.py
from django.db import models
import datetime
# Create your models here.


class Tmbreport (models.Model):
    dateReport = models.DateField()
    dealer = models.IntegerField(default=0)
    pickup = models.IntegerField(default=0)
    rndgal = models.IntegerField(default=0)
    rndEnd = models.IntegerField(default=0)
    badgermeter = models.IntegerField(default=0)
    capsealEnd = models.IntegerField(default=0)
    expensesText = models.TextField(blank=True)
    supplyIns = models.TextField(blank=True)
    dutyText = models.TextField(blank=True)
    cashturnoverCalc = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    cashturnoverRep = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    cashtaken = models.DecimalField(decimal_places=2, max_digits=10, default=0)


class Labreport (models.Model):
    dateReport = models.DateField()
    dealer = models.IntegerField(default=0)
    less = models.IntegerField(default=0)
    pickup = models.IntegerField(default=0)
    smallText = models.IntegerField(default=0)
    goodly = models.IntegerField(default=0)
    square = models.IntegerField(default=0)
    rndgal = models.IntegerField(default=0)
    rndEnd = models.IntegerField(default=0)
    badgermeter = models.IntegerField(default=0)
    capsealEnd = models.IntegerField(default=0)
    squareSlEnd = models.IntegerField(default=0)
    supplyIns = models.TextField(blank=True)
    expensesText = models.TextField(blank=True)
    dutyText = models.TextField(blank=True)
    cashturnoverCalc = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    cashturnoverRep = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    cashtaken = models.DecimalField(decimal_places=2, max_digits=10, default=0)


class Kalimpreport (models.Model):
    dateReport = models.DateField()
    dealer = models.IntegerField(default=0)
    less = models.IntegerField(default=0)
    pickup = models.IntegerField(default=0)
    smallText = models.IntegerField(default=0)
    bakeryGal = models.IntegerField(default=0)
    square = models.IntegerField(default=0)
    smallSquare = models.IntegerField(default=0)
    rndgal = models.IntegerField(default=0)
    rndEnd = models.IntegerField(default=0)
    badgermeter = models.IntegerField(default=0)
    capsealEnd = models.IntegerField(default=0)
    squareSlEnd = models.IntegerField(default=0)
    supplyIns = models.TextField(blank=True)
    expensesText = models.TextField(blank=True)
    dutyText = models.TextField(blank=True)
    cashturnoverCalc = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    cashturnoverRep = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    cashtaken = models.DecimalField(decimal_places=2, max_digits=10, default=0)

businessreport/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

businessreport/views.py
from django.http import JsonResponse
from datetime import datetime, timedelta, date
from django.shortcuts import render, redirect
from django.template import loader
from .models import Tmbreport, Labreport, Kalimpreport
from .reportmakerclass import TalambanRef, LabangonRef, KalimpyoRef
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import CreateUserForm
from .decorators import unauthenticated_user, allowed_users, admin_only

# Create your views here.


def getYesterday(date_string):
    now = date(*map(int, date_string.split('-')))
    yesterday = datetime.strftime(now - timedelta(1), '%Y-%m-%d')
    return yesterday


def uli(request):
    context = {}
    return render(request, 'businessreport/home.html', context)


def about(request):
    context = {}
    return render(request, 'businessreport/about.html', context)


@login_required(login_url='businessreport:login')
@allowed_users(allowed_roles=["talamban"])
def tmbindex(request):
    context = {}
    return render(request, 'businessreport/tmb_rep.html', context)


@login_required(login_url='businessreport:login')
@allowed_users(allowed_roles=["labangon"])
def labindex(request):
    context = {}
    return render(request, 'businessreport/lab_rep.html', context)


@login_required(login_url='businessreport:login')
@allowed_users(allowed_roles=["kalimpyo"])
def kalindex(request):
    context = {}
    return render(request, 'businessreport/kalimp_rep.html', context)


@login_required(login_url='businessreport:login')
def moonindex(request):
    context = {}
    return render(request, 'businessreport/moonlit_rep.html', context)


@login_required(login_url='businessreport:login')
def detail(request):
    # display all post values for debugging
    for key, value in request.POST.items():
        print('Key: %s' % (key))
        print('Value %s' % (value))
    if request.POST["location"] == "Talamban":
        tmbRef = TalambanRef(request.POST, request.user.groups.all()[0].name)
        tmbRef.modifyDB()
        context = tmbRef.postToContext()
    elif request.POST["location"] == "Labangon":
        labRef = LabangonRef(request.POST, request.user.groups.all()[0].name)
        labRef.modifyDB()
        context = labRef.postToContext()
    elif request.POST["location"] == "Kalimpyo":
        kalRef = KalimpyoRef(request.POST, request.user.groups.all()[0].name)
        kalRef.modifyDB()
        context = kalRef.postToContext()
    return render(request, 'businessreport/detail_rep.html', context)


def get_data_yesterday(request):
    print(request.POST['dateReport'])
    if request.POST["location"] == "Talamban":
        tmbRef = TalambanRef(request.POST, request.user.groups.all()[0].name)
        jsonData = tmbRef.ajax_yesterday()
        return JsonResponse(jsonData)
    elif request.POST["location"] == "Labangon":
        labRef = LabangonRef(request.POST, request.user.groups.all()[0].name)
        jsonData = labRef.ajax_yesterday()
        return JsonResponse(jsonData)
    elif request.POST["location"] == "Kalimpyo":
        kalRef = KalimpyoRef(request.POST, request.user.groups.all()[0].name)
        jsonData = kalRef.ajax_yesterday()
        return JsonResponse(jsonData)
    else:
        return JsonResponse({})


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('businessreport:uli')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            dictUser = {"talamban": "tmbrep",
                        "labangon": "labrep", "kalimpyo": "kalrep", "admin": "uli"}
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                group = user.groups.all()[0].name
                return redirect('businessreport:{0}'.format(dictUser[group]))
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'registration/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('businessreport:login')

businessreport/templates/businessreport/about.html
{% extends "businessreport/base_rep.html" %} 
{% block content %}
<ul class="list-group">
  <li class="list-group-item"><strong>About This Website</strong></li>
  <li class="list-group-item">This website is written by Adam Robert So</li>
  <li class="list-group-item">Copyrighted by fcc</li>
</ul>
{% endblock content %}

businessreport/templates/businessreport/base_rep.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'staticreport/main.css' %}"
    />

    {% if title %}
    <title>Helpersite - {{ title }}</title>
    {% else %}
    <title>Helpersite</title>
    {% endif %}
  </head>
  <body>
    <a href="{% url 'businessreport:uli' %}">Home</a> |
    <a href="{% url 'businessreport:about' %}">About</a>
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

businessreport/templates/businessreport/detail_rep.html
{% extends "businessreport/base_rep.html" %}
{% block content %}
{% if location == "Talamban" %}
    <a href="{% url 'businessreport:tmbrep' %}">Go back To Talamban Report Page</a>
    <h1>{{ location }}</h1>
    <span> {{ dateReport }} {{ dayOfWeek }} : {{ duties }} </span><br>
    <span>D{{ dealText }} P{{ pickText }} + Rnd {{ rndText }}</span><br>
    <span>{{ htmlDisplaySales }}</span><br>
    <span>{{ TA }}TA - ({{ expensesText }}) {{ htmlCashTkn }} = {{ ctoCalc }} CTO {{ ctoRep }} {{ htmlShortCTO }}</span><br>
    <span>{{ htmlShortSl }}</span><br>
    <span> {{ htmlShortRnd }} </span><br>
    <span> {{ htmlShortbdgMeter }} </span><br>
{% elif location == "Labangon" %}
    <a href="{% url 'businessreport:labrep' %}">Go back To Labangon Report Page</a>
    <h1>{{ location }}</h1>
    <span> {{ dateReport }} {{ dayOfWeek }} : {{ duties }} </span><br>
    <span>D{{ dealText }}-{{ less }}={{ dealLess }} P{{ pickText }}{{ htmlSmall }}{{ htmlSquare }}{{ htmlGoodly }} + Rnd {{ rndText }}</span><br>
    <span>{{ htmlDisplaySales }}</span><br>
    <span>{{ TA }}TA - ({{ expensesText }}) {{ htmlCashTkn }} = {{ ctoCalc }} CTO {{ ctoRep }} {{ htmlShortCTO }}</span><br>
    <span>{{ htmlShortSl }}</span><br>
    <span>{{ htmlShortSq }}</span><br>    
    <span> {{ htmlShortRnd }} </span><br>
    <span> {{ htmlShortbdgMeter }} </span><br>
{% elif location == "Kalimpyo" %}
    <a href="{% url 'businessreport:kalrep' %}">Go back To Kalimpyo Report Page</a>
    <h1>{{ location }}</h1>
    <span> {{ dateReport }} {{ dayOfWeek }} : {{ duties }} </span><br>
    <span>D{{ dealText }}-{{ less }}={{ dealLess }} P{{ pickText }}{{ htmlSmall }}{{ htmlSquare }}{{ htmlGoodly }}{{ htmlSmallSq }}{{ htmlBkry}} + Rnd {{ rndText }}</span><br>
    <span>{{ htmlDisplaySales }}</span><br>
    <span>{{ TA }}TA - ({{ expensesText }}) {{ htmlCashTkn }} = {{ ctoCalc }} CTO {{ ctoRep }} {{ htmlShortCTO }}</span><br>
    <span>{{ htmlShortSl }}</span><br>
    <span>{{ htmlShortSq }}</span><br>    
    <span> {{ htmlShortRnd }} </span><br>
    <span> {{ htmlShortbdgMeter }} </span><br>
{% endif %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

{% endblock content %}

businessreport/templates/businessreport/home.html
{% extends "businessreport/base_rep.html" %}
{% block content %}

<h1> Applications </h1>
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'js_app:capsealcounter' %}">Cap Seal Counter</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'js_app:moneycounter' %}">Money Counter</a>
    </li>
  </ul>
</nav>

<h1> Report Maker </h1>
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'js_app:labreport' %}">Labangon Report Maker</a>
    </li>

  </ul>
</nav>

<h1> Business Reports </h1>
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'businessreport:tmbrep' %}">Talamban Report</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'businessreport:labrep' %}">Labangon Report</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'businessreport:kalrep' %}">Kalimpyo Report</a>
    </li>
  </ul>
</nav>
{% endblock content %}

businessreport/templates/businessreport/kalimp_rep.html
{% extends "businessreport/base_rep.html" %} 
{% load static %}

{% block content %}
<a href="{% url 'businessreport:logout' %}"> Log out </a>
<h3 class="row">Kalimpyo</h1>
<form method="POST" action="{% url 'businessreport:detailrep' %}">
  {% csrf_token %}
  <div class="form-group">
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Date</span>
      </div>
      <input
        class="form-control"
        type="date"
        value=""
        name="dateReport"
        id="dateReport"
      />
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Dealer</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="dealText"
        name="dealText"
      />
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Less</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="less"
        name="less"
      />
      <span class="input-group-text text-danger" id="dealSales"></span>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Pickup</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="pickText"
        name="pickText"
      />
      <span class="input-group-text text-danger" id="pickSales"></span>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Small</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="smallText"
        name="smallText"
      />
      <span class="input-group-text text-danger" id="smallSales"></span>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Square</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="squareText"
        name="squareText"
      />
      <span class="input-group-text text-danger" id="squareSales"></span>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Small Square</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="smallSquare"
        name="smallSquare"
      />
      <span class="input-group-text text-danger" id="smallSquareSales"></span>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Bakery Gallons</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="bakeryGal"
        name="bakeryGal"
      />
      <span class="input-group-text text-danger" id="bakeryGalSales"></span>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Round Gallons</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="rndText"
        name="rndText"
      />
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Round Beg</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="rndBeg"
        name="rndBeg"
      />
      <div class="input-group-append" id="">
        <div class="input-group-prepend">
          <span class="input-group-text" id="">Round End</span>
        </div>
        <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="rndEnd"
          name="rndEnd"
        />
        <span class="input-group-text text-danger" id="isShortRnd"></span>
        <span class="input-group-text text-danger">IN</span>
        <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="rndIn"
          name="rndIn"
        />
      </div>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Cap Seal Beg</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="cpSealBeg"
        name="cpSealBeg"
      />
      <div class="input-group-append" id="">
        <span class="input-group-text" id="">Cap Seal End</span>
        <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="cpSeal"
          name="cpSeal"
        />
        <span class="input-group-text text-danger" id="isShortCapSl"></span>
        <span class="input-group-text text-danger">IN</span>
        <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="cpSealIn"
          name="cpSealIn"
        />
      </div>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Square Seal Beg</span>
      </div>
      <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="sqSealBeg"
          name="sqSealBeg"
      />
      <div class="input-group-append" id="">
        <span class="input-group-text" id="">Square Seal End</span>
        <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="sqSeal"
          name="sqSeal"
        />
        <span class="input-group-text text-danger" id="isShortSqSl"></span>
        <span class="input-group-text text-danger">IN</span>
        <input
          type="number"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value="0"
          id="sqSealIn"
          name="sqSealIn"
        />
      </div>
    </div>    
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Badger Meter Reading</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="bdgMeter"
        name="bdgMeter"
      />
      <div class="input-group-append" id="">
        <span class="input-group-text text-danger" id="isShortBadger"></span>
      </div>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Expenses</th>
          <th>Amount</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Total</td>
          <td id="totalExpenses">0</td>
        </tr>
        <tr>
          <td>
          <div class="table-button">
            <div class="row">
              <div class="col-sm-2">
                <button type="button" class="btn btn-info add-new">
                  <i class="fa fa-plus"></i> Add Expenses
                </button>
              </div>
            </div>
          </div>  
          </td>
        </tr>
      </tbody>
    </table>
  
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Cash Taken</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="cashTkn"
        name="cashTkn"
      />
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">CTO Calculated</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="ctoCalc"
        name="ctoCalc"
      />
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">CTO Report</span>
      </div>
      <input
        type="number"
        class="form-control"
        placeholder=""
        aria-label=""
        aria-describedby="basic-addon1"
        value="0"
        id="ctoRep"
        name="ctoRep"
      />
      <div class="input-group-append" id="">
        <span class="input-group-text text-danger" id="isShortCTO"></span>
      </div>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Duty #1</span>
      </div>
      <div class="input-group-append" id="">
        <input
          type="text"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value=""
          id="duty1"
        />
        <span class="input-group-text" id="">Duty #2</span>
        <input
          type="text"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value=""
          id="duty2"
        />
      </div>
    </div>
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">Duty #3</span>
      </div>
      <div class="input-group-append" id="">
        <input
          type="text"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value=""
          id="duty3"
        />
        <span class="input-group-text" id="">Duty #4</span>
        <input
          type="text"
          class="form-control"
          placeholder=""
          aria-label=""
          aria-describedby="basic-addon1"
          value=""
          id="duty4"
        />
      </div>
    </div>
    <input type="hidden" id="expensesText" name="expensesText" value="" />
    <input type="hidden" id="totalExpText" name="totalExpText" value="0" />
    <input type="hidden" id="location" name="location" value="Kalimpyo" />
    <input type="hidden" id="duties" name="duties" value="" />
    <button class="btn btn-outline-info" type="submit">Submit</button>
  </div>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'staticreport/ref_rep.js' %}"></script>
{% endblock content %}